# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofolder',
            name='names',
            field=models.CharField(default=' ', max_length=512),
            preserve_default=False,
        ),
    ]
