# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_videofolder_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofolder',
            old_name='names',
            new_name='aliases',
        ),
        migrations.AddField(
            model_name='videofolder',
            name='full_name',
            field=models.CharField(default='eagaeg', max_length=128),
            preserve_default=False,
        ),
    ]
