# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
